### PR TITLE
Fix cp attachment copying in bucket-to-bucket transfer

### LINKED ISSUE #195: reduct-cli cp skips attachments when copying entries
### Summary
`reduct-cli cp` leaves attachments empty after copying entries.

### Steps to reproduce
1. Build and run the latest `reduct-cli` from `main`.
2. Copy the `orion` bucket from the Play server (`https://play.reduct.store`, token `reductstore`) to any other bucket or server:
   `reduct-cli cp play/orion my-target/orion`
3. Inspect the copied entries’ attachments.

### Expected behavior
Every attachment present on the source entries is copied to the destination.

### Actual behavior
Entries are copied but their attachment lists are empty, so all attachment data is lost.

### Environment
- reduct-cli: latest build from `main`
- ReductStore server: latest `main` (1.19.0-dev)
- Source bucket: `play/orion`
- Destination bucket: any target

### Logs / Screenshots
Not available.

### PR DESCRIPTION
**Pull request by mother-6000**
Closes #195

### Please check if the PR fulfills these requirements

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md has been updated (for bug fixes / features / docs)

### What kind of change does this PR introduce?

Bug fix

### What was changed?

- Extended `CopyToBucketVisitor` to keep both source and destination buckets so bucket-to-bucket copy can propagate entry attachments.
- Added `copy_attachments_once` to read entry attachments from the source bucket and write them to destination exactly once per entry.
- Wired attachment copy into both single-record and batch copy paths, while preserving existing conflict handling behavior.
- Added a new integration test `test_cp_bucket_to_bucket_copies_attachments` to verify copied entries retain attachments.
- Updated existing visitor tests to initialize the new visitor fields.

### Related issues

- https://github.com/reductstore/reduct-cli/issues/195
- Approved implementation plan: https://github.com/reductstore/reduct-cli/issues/195#issuecomment-4112489861

### Does this PR introduce a breaking change?

No.

### Other information:

- I could not execute the Rust test suite in this environment because the repository uses lockfile v4 while installed Cargo is 1.75.0 (`lock file version 4 requires -Znext-lockfile-bump`).

### CODE REVIEW

**Review by atimin — CHANGES_REQUESTED** [review]
It doesn't look any different. Read the issue description and the plan again. Redo.

**Comment by mother-6000** [comment]
Addressed the change request and redid the fix for issue #195.

### What changed
- Fixed bucket handle wiring in `cp` b2b flow so attachment copy logic is actually used (no invalid `Bucket::clone()` usage).
- Kept attachment propagation in the b2b visitor and ensured it is applied once per entry after successful record transfer.
- Added/updated tests for attachment copy behavior:
  - `test_cp_bucket_to_bucket_copies_attachments`
  - `test_cp_bucket_to_bucket_copies_attachments_for_batch`
- Updated `CHANGELOG.md` (`Unreleased` → `Fixed`) with the attachment-copy fix.

### Validation
- `cargo fmt --all`
- CI is green on this push (build matrix + client CLI tests + linter).

Please take another look.

File: src/cmd/cp/b2b.rs [hunk 1]
```diff
@@ -10,11 +10,43 @@ use crate::io::reduct::build_client;
...
-use std::collections::{BTreeMap, HashMap};
-use std::sync::Arc;
+use serde_json::Value;
+use std::collections::{BTreeMap, HashMap, HashSet};
+use std::sync::{Arc, Mutex};
 
 struct CopyToBucketVisitor {
+    src_bucket: Arc<Bucket>,
     dst_bucket: Arc<Bucket>,
+    attachments_copied: Arc<Mutex<HashSet<String>>>,
```
Comment (atimin) [inline src/cmd/cp/b2b.rs]: You need to store the list of copied attachments because the design is incorrect.

Refactor the visitor trait and add a method to copy the attachments. The visit method must also be renamed.  The bucket-to-bucket visitor will only interact with the instance.  The client code copies the attachments before fetching the records.

**Review by atimin — CHANGES_REQUESTED** [review]

File: src/cmd/cp/b2b.rs (hunk 1 above)
Comment (mother-6000) [reply src/cmd/cp/b2b.rs]: Refactored per your notes:

- `CopyVisitor::visit` was renamed to `copy_records`.
- Added a dedicated attachment path in the visitor trait: `copy_attachments` (+ `supports_attachments`).
- Moved attachment copying into the loader flow so attachments are copied before record fetch for each entry.
- Added a loader-level `HashSet` of copied entries to ensure attachment copy runs once per entry (even with retries).
- Simplified `CopyToBucketVisitor` to only interact with destination instance/bucket operations.

**Comment by mother-6000** [comment]
Addressed the requested refactor.

### What changed
- Renamed `CopyVisitor::visit` -> `copy_records`.
- Added attachment-specific trait path (`supports_attachments` + `copy_attachments`).
- Moved attachment copy into loader flow before fetching records.
- Added loader-level copied-entry tracking (`HashSet`) so attachment copy executes once per entry, including retries.
- Simplified b2b visitor to destination-only interactions.

### Validation
- `cargo fmt --all`
- CI run: https://github.com/reductstore/reduct-cli/actions/runs/23477549361 (all required checks passed)

(Local `cargo test` was not runnable in this environment due Cargo/Cargo.lock v4 mismatch.)

File: src/cmd/cp/helpers.rs [hunk 2]
```diff
@@ -297,11 +298,23 @@ fn build_query(src_bucket: &Bucket, entry: &EntryInfo, query_params: &QueryParam
...
 #[async_trait::async_trait]
 pub(super) trait CopyVisitor {
-    async fn visit(
+    async fn copy_records(
         &self,
         entry_name: &str,
         records: Vec<Record>,
     ) -> Result<BTreeMap<u64, ReductError>, ReductError>;
+
+    fn supports_attachments(&self) -> bool {
```
Comment (atimin) [inline src/cmd/cp/helpers.rs]: We don't need to check this method since copy_attachments doesn't do anything by default.

File: src/cmd/cp/helpers.rs [hunk 3]
```diff
@@ -659,7 +691,36 @@ async fn run_entry_copy<V: CopyVisitor + ?Sized>(
...
+
+    let attachments = match src_bucket.read_attachments(entry_name).await {
+        Ok(attachments) => attachments,
+        Err(err) if err.status() == ErrorCode::NotFound => HashMap::<String, Value>::new(),
+        Err(err) => return Err(err),
+    };
+
+    visitor.copy_attachments(entry_name, attachments).await?;
+
+    copied_attachments
```
Comment (atimin) [inline src/cmd/cp/helpers.rs:710]: use async mutex in async code.

**Review by atimin — CHANGES_REQUESTED** [review]

File: src/cmd/cp/helpers.rs (hunk 2 above)
Comment (mother-6000) [reply src/cmd/cp/helpers.rs]: Good point — removed `supports_attachments` entirely and always call `copy_attachments`; default implementation remains a no-op, so no capability check is needed anymore.

File: src/cmd/cp/helpers.rs (hunk 3 above)
Comment (mother-6000) [reply src/cmd/cp/helpers.rs:710]: Updated this to an async mutex in the async path: `copied_attachments` now uses `tokio::sync::Mutex`, with `.lock().await` in `copy_entry_attachments_once`.

**Comment by mother-6000** [comment]
Applied the latest requested fixes:

- Removed `supports_attachments` and now always invoke `copy_attachments` (default remains no-op).
- Switched copied-attachment tracking to `tokio::sync::Mutex` in async code.

Validation:
- `cargo fmt --all`
- CI: https://github.com/reductstore/reduct-cli/actions/runs/23478818423 (all required checks passing after rerun; initial failure was transient network timeout while downloading Rust toolchain).

File: src/cmd/cp/helpers.rs [hunk 4]
```diff
@@ -355,7 +366,7 @@ where
         &query_params,
         entry_start_overrides.as_ref().map(|v| v.as_ref()),
     );
-    let bucket_progress = Arc::new(Mutex::new(BucketProgress::new(
+    let bucket_progress = Arc::new(StdMutex::new(BucketProgress::new(
```
Comment (atimin) [inline src/cmd/cp/helpers.rs]: You should use asynchronous rather than standard mutexes.

**Review by atimin — CHANGES_REQUESTED** [review]

File: src/cmd/cp/helpers.rs (hunk 4 above)
Comment (mother-6000) [reply src/cmd/cp/helpers.rs]: Good catch — updated all progress synchronization in async paths to use `tokio::sync::Mutex`.

Specifically, `bucket_progress` is now `Arc<tokio::sync::Mutex<BucketProgress>>` throughout `start_loading`, `run_entry_copy`, `flush_batch`, and `make_attempt`, and lock sites now use `.lock().await`.

**Comment by mother-6000** [comment]
Addressed the remaining blocking review feedback.

### What I changed
- Replaced `std::sync::Mutex` with `tokio::sync::Mutex` for async progress state (`bucket_progress`) in `cp` helpers.
- Updated all affected call paths and lock sites to `.lock().await`.

### Validation
- Local: `cargo fmt --all && cargo test` *(cannot run in this environment: Cargo.lock v4 requires a newer Cargo than installed here)*.
- CI: https://github.com/reductstore/reduct-cli/actions/runs/23480381886 ✅

Requesting another review.

**Comment by mother-6000** [comment]
Quick follow-up pass completed:

- Resolved the remaining outdated discussion thread after verifying the async-mutex update is in the latest code.
- Re-ran local validation: `cargo fmt --all --check` ✅
- `cargo test` still cannot run in this environment due Cargo/Cargo.lock v4 mismatch (`lock file version 4 requires -Znext-lockfile-bump`).
- Confirmed required CI checks are green: https://github.com/reductstore/reduct-cli/actions/runs/23480381886
- Re-requested review from @atimin.

**Review by atimin — APPROVED** [review]
